source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'pg'
gem "private_pub", "~> 1.0.3"
gem 'simple_form'
gem "cancan"
gem "bcrypt-ruby", "~> 3.0.1"

group :development do
  gem 'sqlite3'
  gem 'annotate', '~> 2.4.1.beta'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'twitter-bootstrap-rails'
  gem 'less-rails'

end

gem 'jquery-rails'
gem 'thin'

